ALTER TABLE "ward_councils"
  ADD COLUMN "status" text DEFAULT 'programado',
  ADD COLUMN "started_at" timestamp,
  ADD COLUMN "ended_at" timestamp,
  ADD COLUMN "opening_prayer" text,
  ADD COLUMN "opening_hymn" text,
  ADD COLUMN "spiritual_thought" text,
  ADD COLUMN "spiritual_thought_by" text,
  ADD COLUMN "spiritual_thought_topic" text,
  ADD COLUMN "previous_assignments" jsonb DEFAULT '[]'::jsonb,
  ADD COLUMN "adjustments_notes" text,
  ADD COLUMN "ministry_notes" text,
  ADD COLUMN "salvation_work_notes" text,
  ADD COLUMN "ward_activities_notes" text,
  ADD COLUMN "new_assignments_notes" text,
  ADD COLUMN "final_summary_notes" text,
  ADD COLUMN "closing_prayer" text,
  ADD COLUMN "closing_prayer_by" text,
  ADD COLUMN "bishop_notes" text;
