-- No schema changes needed for niño inscrito baptisms.
-- Candidate names are stored as baptism_program_items (type='candidato_nombre').
-- persona_id cannot be made nullable because it is part of the primary key.
