/**
 * Idempotent startup migrations for the hymns table.
 * Run once on server boot; safe to re-run (ON CONFLICT + WHERE external_url IS NULL).
 */
import { sql } from "drizzle-orm";
import { db } from "./db";

export async function applyHymnStartupMigrations(_db?: unknown) {
  // Ensure columns exist (migration 0048 — safe no-op if already present)
  await db.execute(sql`ALTER TABLE hymns ADD COLUMN IF NOT EXISTS hymnbook text NOT NULL DEFAULT 'default'`);
  await db.execute(sql`ALTER TABLE hymns ADD COLUMN IF NOT EXISTS lang text NOT NULL DEFAULT 'es'`);
  await db.execute(sql`ALTER TABLE hymns ADD COLUMN IF NOT EXISTS external_url text`);
  await db.execute(sql`ALTER TABLE hymns ADD COLUMN IF NOT EXISTS number_display text`);

  // Fix unique index: (number) → (number, hymnbook) to allow primaria to share numbers with himnario
  await db.execute(sql`DROP INDEX IF EXISTS hymns_number_unique`);
  await db.execute(sql`CREATE UNIQUE INDEX IF NOT EXISTS hymns_number_hymnbook_unique ON hymns (number, hymnbook)`);

  // Classify existing hymns by hymnbook
  await db.execute(sql`UPDATE hymns SET hymnbook = 'himnario'      WHERE number BETWEEN 1 AND 209   AND hymnbook = 'default'`);
  await db.execute(sql`UPDATE hymns SET hymnbook = 'hogar_iglesia' WHERE number >= 1001              AND hymnbook = 'default'`);

  // Insert missing new-hymnbook entries (migration 0084)
  await db.execute(sql`
    INSERT INTO hymns (number, hymnbook, title) VALUES
      (1052, 'hogar_iglesia', '¡Oh, qué gozo nos da!'),
      (1053, 'hogar_iglesia', 'Mis convenios'),
      (1054, 'hogar_iglesia', 'Al bautizarme a Cristo seguiré'),
      (1055, 'hogar_iglesia', 'El poder del Santo Espíritu'),
      (1056, 'hogar_iglesia', 'Elías y la suave voz'),
      (1057, 'hogar_iglesia', 'Mi pastor es Cristo'),
      (1058, 'hogar_iglesia', 'Mi canto en la noche'),
      (1059, 'hogar_iglesia', 'El mundo es de Dios'),
      (1060, 'hogar_iglesia', 'Un arca construiré'),
      (1061, 'hogar_iglesia', 'Cuán dulce hogar de amor'),
      (1062, 'hogar_iglesia', 'Nuestro ayuno, oh, Señor'),
      (1210, 'hogar_iglesia', 'Tiempo atrás, en un jardín')
    ON CONFLICT (number, hymnbook) DO NOTHING
  `);

  // Set external_url for all hymns (migrations 0083 + 0084 URL section)
  // Only updates rows where external_url is not yet set — safe to re-run.
  await db.execute(sql`
    UPDATE hymns SET external_url = v.url
    FROM (VALUES
      (1,   'https://www.churchofjesuschrist.org/study/manual/hymns/the-morning-breaks?lang=spa'),
      (2,   'https://www.churchofjesuschrist.org/study/manual/hymns/the-spirit-of-god?lang=spa'),
      (3,   'https://www.churchofjesuschrist.org/study/manual/hymns/now-let-us-rejoice?lang=spa'),
      (4,   'https://www.churchofjesuschrist.org/study/manual/hymns/high-on-the-mountain-top?lang=spa'),
      (5,   'https://www.churchofjesuschrist.org/study/manual/hymns/redeemer-of-israel?lang=spa'),
      (6,   'https://www.churchofjesuschrist.org/study/manual/hymns/israel-israel-god-is-calling?lang=spa'),
      (7,   'https://www.churchofjesuschrist.org/study/manual/hymns/go-ye-messengers-of-heaven?lang=spa'),
      (8,   'https://www.churchofjesuschrist.org/study/manual/hymns/what-was-witnessed-in-the-heavens?lang=spa'),
      (9,   'https://www.churchofjesuschrist.org/study/manual/hymns/an-angel-from-on-high?lang=spa'),
      (10,  'https://www.churchofjesuschrist.org/study/manual/hymns/we-thank-thee-o-god-for-a-prophet?lang=spa'),
      (11,  'https://www.churchofjesuschrist.org/study/manual/hymns/come-listen-to-a-prophets-voice?lang=spa'),
      (12,  'https://www.churchofjesuschrist.org/study/manual/hymns/we-ever-pray-for-thee?lang=spa'),
      (13,  'https://www.churchofjesuschrist.org/study/manual/hymns/god-bless-our-prophet-dear?lang=spa'),
      (14,  'https://www.churchofjesuschrist.org/study/manual/hymns/joseph-smiths-first-prayer?lang=spa'),
      (15,  'https://www.churchofjesuschrist.org/study/manual/hymns/praise-to-the-man?lang=spa'),
      (16,  'https://www.churchofjesuschrist.org/study/manual/hymns/a-poor-wayfaring-man-of-grief?lang=spa'),
      (17,  'https://www.churchofjesuschrist.org/study/manual/hymns/come-come-ye-saints?lang=spa'),
      (18,  'https://www.churchofjesuschrist.org/study/manual/hymns/o-ye-mountains-high?lang=spa'),
      (19,  'https://www.churchofjesuschrist.org/study/manual/hymns/for-the-strength-of-the-hills?lang=spa'),
      (20,  'https://www.churchofjesuschrist.org/study/manual/hymns/the-happy-day-at-last-has-come?lang=spa'),
      (21,  'https://www.churchofjesuschrist.org/study/manual/hymns/hail-to-the-brightness-of-zions-glad-morning?lang=spa'),
      (22,  'https://www.churchofjesuschrist.org/study/manual/hymns/zion-stands-with-hills-surrounded?lang=spa'),
      (23,  'https://www.churchofjesuschrist.org/study/manual/hymns/beautiful-zion-built-above?lang=spa'),
      (24,  'https://www.churchofjesuschrist.org/study/manual/hymns/the-day-dawn-is-breaking?lang=spa'),
      (25,  'https://www.churchofjesuschrist.org/study/manual/hymns/lo-the-mighty-god-appearing?lang=spa'),
      (26,  'https://www.churchofjesuschrist.org/study/manual/hymns/come-ye-children-of-the-lord?lang=spa'),
      (27,  'https://www.churchofjesuschrist.org/study/manual/hymns/come-o-thou-king-of-kings?lang=spa'),
      (28,  'https://www.churchofjesuschrist.org/study/manual/hymns/battle-hymn-of-the-republic?lang=spa'),
      (29,  'https://www.churchofjesuschrist.org/study/manual/hymns/come-thou-glorious-day-of-promise?lang=spa'),
      (30,  'https://www.churchofjesuschrist.org/study/manual/hymns/rejoice-the-lord-is-king?lang=spa'),
      (31,  'https://www.churchofjesuschrist.org/study/manual/hymns/all-creatures-of-our-god-and-king?lang=spa'),
      (32,  'https://www.churchofjesuschrist.org/study/manual/hymns/a-mighty-fortress-is-our-god?lang=spa'),
      (33,  'https://www.churchofjesuschrist.org/study/manual/hymns/all-glory-laud-and-honor?lang=spa'),
      (34,  'https://www.churchofjesuschrist.org/study/manual/hymns/god-of-our-fathers-whose-almighty-hand?lang=spa'),
      (35,  'https://www.churchofjesuschrist.org/study/manual/hymns/god-of-our-fathers-known-of-old-woodbury?lang=spa'),
      (36,  'https://www.churchofjesuschrist.org/study/manual/hymns/god-of-our-fathers-we-come-unto-thee?lang=spa'),
      (37,  'https://www.churchofjesuschrist.org/study/manual/hymns/glory-to-god-on-high?lang=spa'),
      (38,  'https://www.churchofjesuschrist.org/study/manual/hymns/press-forward-saints?lang=spa'),
      (39,  'https://www.churchofjesuschrist.org/study/manual/hymns/guide-us-o-thou-great-jehovah-harrison?lang=spa'),
      (40,  'https://www.churchofjesuschrist.org/study/manual/hymns/how-firm-a-foundation?lang=spa'),
      (41,  'https://www.churchofjesuschrist.org/study/manual/hymns/how-great-thou-art?lang=spa'),
      (42,  'https://www.churchofjesuschrist.org/study/manual/hymns/the-lord-is-my-light?lang=spa'),
      (43,  'https://www.churchofjesuschrist.org/study/manual/hymns/for-the-beauty-of-the-earth?lang=spa'),
      (44,  'https://www.churchofjesuschrist.org/study/manual/hymns/god-is-love?lang=spa'),
      (45,  'https://www.churchofjesuschrist.org/study/manual/hymns/prayer-of-thanksgiving?lang=spa'),
      (46,  'https://www.churchofjesuschrist.org/study/manual/hymns/come-ye-thankful-people?lang=spa'),
      (47,  'https://www.churchofjesuschrist.org/study/manual/hymns/dearest-children-god-is-near-you?lang=spa'),
      (48,  'https://www.churchofjesuschrist.org/study/manual/hymns/lead-kindly-light?lang=spa'),
      (49,  'https://www.churchofjesuschrist.org/study/manual/hymns/i-need-thee-every-hour?lang=spa'),
      (50,  'https://www.churchofjesuschrist.org/study/manual/hymns/nearer-my-god-to-thee?lang=spa'),
      (51,  'https://www.churchofjesuschrist.org/study/manual/hymns/jesus-savior-pilot-me?lang=spa'),
      (52,  'https://www.churchofjesuschrist.org/study/manual/hymns/guide-me-to-thee?lang=spa'),
      (53,  'https://www.churchofjesuschrist.org/study/manual/hymns/jesus-lover-of-my-soul?lang=spa'),
      (54,  'https://www.churchofjesuschrist.org/study/manual/hymns/master-the-tempest-is-raging?lang=spa'),
      (55,  'https://www.churchofjesuschrist.org/study/manual/hymns/god-speed-the-right?lang=spa'),
      (56,  'https://www.churchofjesuschrist.org/study/manual/hymns/the-lord-is-my-shepherd?lang=spa'),
      (57,  'https://www.churchofjesuschrist.org/study/manual/hymns/our-saviors-love?lang=spa'),
      (58,  'https://www.churchofjesuschrist.org/study/manual/hymns/rock-of-ages?lang=spa'),
      (59,  'https://www.churchofjesuschrist.org/study/manual/hymns/behold-the-lamb-of-god?lang=spa'),
      (60,  'https://www.churchofjesuschrist.org/study/manual/hymns/come-unto-jesus?lang=spa'),
      (61,  'https://www.churchofjesuschrist.org/study/manual/hymns/come-follow-me?lang=spa'),
      (62,  'https://www.churchofjesuschrist.org/study/manual/hymns/take-courage-saints?lang=spa'),
      (63,  'https://www.churchofjesuschrist.org/study/manual/hymns/though-deepening-trials?lang=spa'),
      (64,  'https://www.churchofjesuschrist.org/study/manual/hymns/come-we-that-love-the-lord?lang=spa'),
      (65,  'https://www.churchofjesuschrist.org/study/manual/hymns/unanswered-yet-the-prayer?lang=spa'),
      (66,  'https://www.churchofjesuschrist.org/study/manual/hymns/how-gentle-gods-commands?lang=spa'),
      (67,  'https://www.churchofjesuschrist.org/study/manual/hymns/if-the-way-be-full-of-trial?lang=spa'),
      (68,  'https://www.churchofjesuschrist.org/study/manual/hymns/when-faith-endures?lang=spa'),
      (69,  'https://www.churchofjesuschrist.org/study/manual/hymns/where-can-i-turn-for-peace?lang=spa'),
      (70,  'https://www.churchofjesuschrist.org/study/manual/hymns/be-thou-humble?lang=spa'),
      (71,  'https://www.churchofjesuschrist.org/study/manual/hymns/more-holiness-give-me?lang=spa'),
      (72,  'https://www.churchofjesuschrist.org/study/manual/hymns/i-believe-in-christ?lang=spa'),
      (73,  'https://www.churchofjesuschrist.org/study/manual/hymns/i-know-that-my-redeemer-lives?lang=spa'),
      (74,  'https://www.churchofjesuschrist.org/study/manual/hymns/my-redeemer-lives?lang=spa'),
      (75,  'https://www.churchofjesuschrist.org/study/manual/hymns/testimony?lang=spa'),
      (76,  'https://www.churchofjesuschrist.org/study/manual/hymns/jesus-the-very-thought-of-thee?lang=spa'),
      (77,  'https://www.churchofjesuschrist.org/study/manual/hymns/let-the-holy-spirit-guide?lang=spa'),
      (78,  'https://www.churchofjesuschrist.org/study/manual/hymns/sweet-hour-of-prayer?lang=spa'),
      (79,  'https://www.churchofjesuschrist.org/study/manual/hymns/prayer-is-the-souls-sincere-desire?lang=spa'),
      (80,  'https://www.churchofjesuschrist.org/study/manual/hymns/secret-prayer?lang=spa'),
      (81,  'https://www.churchofjesuschrist.org/study/manual/hymns/did-you-think-to-pray?lang=spa'),
      (82,  'https://www.churchofjesuschrist.org/study/manual/hymns/father-in-heaven?lang=spa'),
      (83,  'https://www.churchofjesuschrist.org/study/manual/hymns/gently-raise-the-sacred-strain?lang=spa'),
      (84,  'https://www.churchofjesuschrist.org/study/manual/hymns/sweet-is-the-work?lang=spa'),
      (85,  'https://www.churchofjesuschrist.org/study/manual/hymns/sweet-sabbath-day?lang=spa'),
      (86,  'https://www.churchofjesuschrist.org/study/manual/hymns/o-thou-kind-and-gracious-father?lang=spa'),
      (87,  'https://www.churchofjesuschrist.org/study/manual/hymns/as-the-dew-from-heaven-distilling?lang=spa'),
      (88,  'https://www.churchofjesuschrist.org/study/manual/hymns/how-pleasing-it-is-to-work?lang=spa'),
      (89,  'https://www.churchofjesuschrist.org/study/manual/hymns/god-be-with-you-till-we-meet-again?lang=spa'),
      (90,  'https://www.churchofjesuschrist.org/study/manual/hymns/lord-we-ask-thee-ere-we-part?lang=spa'),
      (91,  'https://www.churchofjesuschrist.org/study/manual/hymns/sing-we-now-at-parting?lang=spa'),
      (92,  'https://www.churchofjesuschrist.org/study/manual/hymns/we-have-partaken-of-thy-love?lang=spa'),
      (93,  'https://www.churchofjesuschrist.org/study/manual/hymns/before-thee-lord-i-bow-my-head?lang=spa'),
      (94,  'https://www.churchofjesuschrist.org/study/manual/hymns/now-the-day-is-over?lang=spa'),
      (95,  'https://www.churchofjesuschrist.org/study/manual/hymns/thy-spirit-lord-has-stirred-our-souls?lang=spa'),
      (96,  'https://www.churchofjesuschrist.org/study/manual/hymns/softly-now-the-light-of-day?lang=spa'),
      (97,  'https://www.churchofjesuschrist.org/study/manual/hymns/lord-we-come-before-thee-now?lang=spa'),
      (98,  'https://www.churchofjesuschrist.org/study/manual/hymns/abide-with-me-tis-eventide?lang=spa'),
      (99,  'https://www.churchofjesuschrist.org/study/manual/hymns/abide-with-me?lang=spa'),
      (100, 'https://www.churchofjesuschrist.org/study/manual/hymns/lord-dismiss-us-with-thy-blessing?lang=spa'),
      (101, 'https://www.churchofjesuschrist.org/study/manual/hymns/god-our-father-hear-us-pray?lang=spa'),
      (102, 'https://www.churchofjesuschrist.org/study/manual/hymns/in-humility-our-savior?lang=spa'),
      (103, 'https://www.churchofjesuschrist.org/study/manual/hymns/while-of-these-emblems-we-partake-saul?lang=spa'),
      (104, 'https://www.churchofjesuschrist.org/study/manual/hymns/o-god-the-eternal-father?lang=spa'),
      (105, 'https://www.churchofjesuschrist.org/study/manual/hymns/jesus-of-nazareth-savior-and-king?lang=spa'),
      (106, 'https://www.churchofjesuschrist.org/study/manual/hymns/tis-sweet-to-sing-the-matchless-love-hancock?lang=spa'),
      (107, 'https://www.churchofjesuschrist.org/study/manual/hymns/o-lord-of-hosts?lang=spa'),
      (108, 'https://www.churchofjesuschrist.org/study/manual/hymns/reverently-and-meekly-now?lang=spa'),
      (109, 'https://www.churchofjesuschrist.org/study/manual/hymns/well-sing-all-hail-to-jesus-name?lang=spa'),
      (110, 'https://www.churchofjesuschrist.org/study/manual/hymns/in-remembrance-of-thy-suffering?lang=spa'),
      (111, 'https://www.churchofjesuschrist.org/study/manual/hymns/upon-the-cross-of-calvary?lang=spa'),
      (112, 'https://www.churchofjesuschrist.org/study/manual/hymns/god-loved-us-so-he-sent-his-son?lang=spa'),
      (113, 'https://www.churchofjesuschrist.org/study/manual/hymns/again-we-meet-around-the-board?lang=spa'),
      (114, 'https://www.churchofjesuschrist.org/study/manual/hymns/behold-the-great-redeemer-die?lang=spa'),
      (115, 'https://www.churchofjesuschrist.org/study/manual/hymns/in-memory-of-the-crucified?lang=spa'),
      (116, 'https://www.churchofjesuschrist.org/study/manual/hymns/how-great-the-wisdom-and-the-love?lang=spa'),
      (117, 'https://www.churchofjesuschrist.org/study/manual/hymns/he-died-the-great-redeemer-died?lang=spa'),
      (118, 'https://www.churchofjesuschrist.org/study/manual/hymns/i-stand-all-amazed?lang=spa'),
      (119, 'https://www.churchofjesuschrist.org/study/manual/hymns/there-is-a-green-hill-far-away?lang=spa'),
      (120, 'https://www.churchofjesuschrist.org/study/manual/hymns/jesus-once-of-humble-birth?lang=spa'),
      (121, 'https://www.churchofjesuschrist.org/study/manual/hymns/he-is-risen?lang=spa'),
      (122, 'https://www.churchofjesuschrist.org/study/manual/hymns/christ-the-lord-is-risen-today?lang=spa'),
      (123, 'https://www.churchofjesuschrist.org/study/manual/hymns/joy-to-the-world?lang=spa'),
      (124, 'https://www.churchofjesuschrist.org/study/manual/hymns/oh-come-all-ye-faithful?lang=spa'),
      (125, 'https://www.churchofjesuschrist.org/study/manual/hymns/away-in-a-manger?lang=spa'),
      (126, 'https://www.churchofjesuschrist.org/study/manual/hymns/angels-we-have-heard-on-high?lang=spa'),
      (127, 'https://www.churchofjesuschrist.org/study/manual/hymns/silent-night?lang=spa'),
      (128, 'https://www.churchofjesuschrist.org/study/manual/hymns/it-came-upon-the-midnight-clear?lang=spa'),
      (129, 'https://www.churchofjesuschrist.org/study/manual/hymns/o-little-town-of-bethlehem?lang=spa'),
      (130, 'https://www.churchofjesuschrist.org/study/manual/hymns/hark-the-herald-angels-sing?lang=spa'),
      (131, 'https://www.churchofjesuschrist.org/study/manual/hymns/with-wondering-awe?lang=spa'),
      (132, 'https://www.churchofjesuschrist.org/study/manual/hymns/the-first-noel?lang=spa'),
      (133, 'https://www.churchofjesuschrist.org/study/manual/hymns/i-heard-the-bells-on-christmas-day?lang=spa'),
      (134, 'https://www.churchofjesuschrist.org/study/manual/hymns/far-far-away-on-judeas-plains?lang=spa'),
      (135, 'https://www.churchofjesuschrist.org/study/manual/hymns/we-are-sowing?lang=spa'),
      (136, 'https://www.churchofjesuschrist.org/study/manual/hymns/for-all-the-saints?lang=spa'),
      (137, 'https://www.churchofjesuschrist.org/study/manual/hymns/because-i-have-been-given-much?lang=spa'),
      (138, 'https://www.churchofjesuschrist.org/study/manual/hymns/lord-i-would-follow-thee?lang=spa'),
      (139, 'https://www.churchofjesuschrist.org/study/manual/hymns/dear-to-the-heart-of-the-shepherd?lang=spa'),
      (140, 'https://www.churchofjesuschrist.org/study/manual/hymns/praise-god-from-whom-all-blessings-flow?lang=spa'),
      (141, 'https://www.churchofjesuschrist.org/study/manual/hymns/have-i-done-any-good?lang=spa'),
      (142, 'https://www.churchofjesuschrist.org/study/manual/hymns/one-more-year-has-gone?lang=spa'),
      (143, 'https://www.churchofjesuschrist.org/study/manual/hymns/the-joy-and-the-song?lang=spa'),
      (144, 'https://www.churchofjesuschrist.org/study/manual/hymns/we-are-marching-on-to-glory?lang=spa'),
      (145, 'https://www.churchofjesuschrist.org/study/manual/hymns/improve-the-shining-moments?lang=spa'),
      (146, 'https://www.churchofjesuschrist.org/study/manual/hymns/there-is-sunshine-in-my-soul-today?lang=spa'),
      (147, 'https://www.churchofjesuschrist.org/study/manual/hymns/catch-the-sunshine?lang=spa'),
      (148, 'https://www.churchofjesuschrist.org/study/manual/hymns/you-can-make-the-pathway-bright?lang=spa'),
      (149, 'https://www.churchofjesuschrist.org/study/manual/hymns/today-while-the-sun-shines?lang=spa'),
      (150, 'https://www.churchofjesuschrist.org/study/manual/hymns/scatter-sunshine?lang=spa'),
      (151, 'https://www.churchofjesuschrist.org/study/manual/hymns/let-us-oft-speak-kind-words?lang=spa'),
      (152, 'https://www.churchofjesuschrist.org/study/manual/hymns/angry-words-oh-let-them-never?lang=spa'),
      (153, 'https://www.churchofjesuschrist.org/study/manual/hymns/hark-listen-to-the-trumpeters?lang=spa'),
      (154, 'https://www.churchofjesuschrist.org/study/manual/hymns/do-what-is-right?lang=spa'),
      (155, 'https://www.churchofjesuschrist.org/study/manual/hymns/choose-the-right?lang=spa'),
      (156, 'https://www.churchofjesuschrist.org/study/manual/hymns/jehovah-lord-of-heaven-and-earth?lang=spa'),
      (157, 'https://www.churchofjesuschrist.org/study/manual/hymns/count-your-blessings?lang=spa'),
      (158, 'https://www.churchofjesuschrist.org/study/manual/hymns/let-us-all-press-on?lang=spa'),
      (159, 'https://www.churchofjesuschrist.org/study/manual/hymns/onward-christian-soldiers?lang=spa'),
      (160, 'https://www.churchofjesuschrist.org/study/manual/hymns/we-love-thy-house-o-god?lang=spa'),
      (161, 'https://www.churchofjesuschrist.org/study/manual/hymns/called-to-serve?lang=spa'),
      (162, 'https://www.churchofjesuschrist.org/study/manual/hymns/we-are-all-enlisted?lang=spa'),
      (163, 'https://www.churchofjesuschrist.org/study/manual/hymns/behold-a-royal-army?lang=spa'),
      (164, 'https://www.churchofjesuschrist.org/study/manual/hymns/put-your-shoulder-to-the-wheel?lang=spa'),
      (165, 'https://www.churchofjesuschrist.org/study/manual/hymns/thy-holy-word?lang=spa'),
      (166, 'https://www.churchofjesuschrist.org/study/manual/hymns/true-to-the-faith?lang=spa'),
      (167, 'https://www.churchofjesuschrist.org/study/manual/hymns/carry-on?lang=spa'),
      (168, 'https://www.churchofjesuschrist.org/study/manual/hymns/hope-of-israel?lang=spa'),
      (169, 'https://www.churchofjesuschrist.org/study/manual/hymns/go-forth-with-faith?lang=spa'),
      (170, 'https://www.churchofjesuschrist.org/study/manual/hymns/whos-on-the-lords-side?lang=spa'),
      (171, 'https://www.churchofjesuschrist.org/study/manual/hymns/hark-all-ye-nations?lang=spa'),
      (172, 'https://www.churchofjesuschrist.org/study/manual/hymns/help-me-teach-with-inspiration?lang=spa'),
      (173, 'https://www.churchofjesuschrist.org/study/manual/hymns/the-time-is-far-spent?lang=spa'),
      (174, 'https://www.churchofjesuschrist.org/study/manual/hymns/how-wondrous-and-great?lang=spa'),
      (175, 'https://www.churchofjesuschrist.org/study/manual/hymns/ill-go-where-you-want-me-to-go?lang=spa'),
      (176, 'https://www.churchofjesuschrist.org/study/manual/hymns/oh-holy-words-of-truth-and-love?lang=spa'),
      (177, 'https://www.churchofjesuschrist.org/study/manual/hymns/oh-say-what-is-truth?lang=spa'),
      (178, 'https://www.churchofjesuschrist.org/study/manual/hymns/truth-reflects-upon-our-senses?lang=spa'),
      (179, 'https://www.churchofjesuschrist.org/study/manual/hymns/the-iron-rod?lang=spa'),
      (180, 'https://www.churchofjesuschrist.org/study/manual/hymns/as-i-search-the-holy-scriptures?lang=spa'),
      (181, 'https://www.churchofjesuschrist.org/study/manual/hymns/come-away-to-the-sunday-school?lang=spa'),
      (182, 'https://www.churchofjesuschrist.org/study/manual/hymns/welcome-welcome-sabbath-morning?lang=spa'),
      (183, 'https://www.churchofjesuschrist.org/study/manual/hymns/holy-temples-on-mount-zion?lang=spa'),
      (184, 'https://www.churchofjesuschrist.org/study/manual/hymns/rise-ye-saints-and-temples-enter?lang=spa'),
      (185, 'https://www.churchofjesuschrist.org/study/manual/hymns/the-glorious-gospel-light-has-shone?lang=spa'),
      (186, 'https://www.churchofjesuschrist.org/study/manual/hymns/turn-your-hearts?lang=spa'),
      (187, 'https://www.churchofjesuschrist.org/study/manual/hymns/o-my-father?lang=spa'),
      (188, 'https://www.churchofjesuschrist.org/study/manual/hymns/each-life-that-touches-ours-for-good?lang=spa'),
      (189, 'https://www.churchofjesuschrist.org/study/manual/hymns/o-love-that-glorifies-the-son?lang=spa'),
      (190, 'https://www.churchofjesuschrist.org/study/manual/hymns/beautiful-home?lang=spa'),
      (191, 'https://www.churchofjesuschrist.org/study/manual/hymns/god-moves-in-a-mysterious-way?lang=spa'),
      (192, 'https://www.churchofjesuschrist.org/study/manual/hymns/lord-accept-our-true-devotion?lang=spa'),
      (193, 'https://www.churchofjesuschrist.org/study/manual/hymns/home-can-be-a-heaven-on-earth?lang=spa'),
      (194, 'https://www.churchofjesuschrist.org/study/manual/hymns/love-at-home?lang=spa'),
      (195, 'https://www.churchofjesuschrist.org/study/manual/hymns/families-can-be-together-forever?lang=spa'),
      (196, 'https://www.churchofjesuschrist.org/study/manual/hymns/i-am-a-child-of-god?lang=spa'),
      (197, 'https://www.churchofjesuschrist.org/study/manual/hymns/keep-the-commandments?lang=spa'),
      (198, 'https://www.churchofjesuschrist.org/study/manual/hymns/teach-me-to-walk-in-the-light?lang=spa'),
      (199, 'https://www.churchofjesuschrist.org/study/manual/hymns/i-know-my-father-lives?lang=spa'),
      (200, 'https://www.churchofjesuschrist.org/study/manual/hymns/the-light-divine?lang=spa'),
      (201, 'https://www.churchofjesuschrist.org/study/manual/hymns/gods-daily-care?lang=spa'),
      (202, 'https://www.churchofjesuschrist.org/study/manual/hymns/in-our-lovely-deseret?lang=spa'),
      (203, 'https://www.churchofjesuschrist.org/study/manual/hymns/love-one-another?lang=spa'),
      (204, 'https://www.churchofjesuschrist.org/study/manual/hymns/children-of-our-heavenly-father?lang=spa'),
      (205, 'https://www.churchofjesuschrist.org/study/manual/hymns/as-sisters-in-zion-women?lang=spa'),
      (206, 'https://www.churchofjesuschrist.org/study/manual/hymns/come-all-ye-sons-of-god-men?lang=spa'),
      (207, 'https://www.churchofjesuschrist.org/study/manual/hymns/ye-who-are-called-to-labor-men?lang=spa'),
      (208, 'https://www.churchofjesuschrist.org/study/manual/hymns/brightly-beams-our-fathers-mercy-men?lang=spa'),
      (209, 'https://www.churchofjesuschrist.org/study/manual/hymns/ye-elders-of-israel-men?lang=spa'),
      (1001, 'https://www.churchofjesuschrist.org/study/music/hymns-for-home-and-church/come-thou-fount-of-every-blessing?lang=spa'),
      (1002, 'https://www.churchofjesuschrist.org/study/music/hymns-for-home-and-church/when-the-savior-comes-again?lang=spa'),
      (1003, 'https://www.churchofjesuschrist.org/study/music/hymns-for-home-and-church/it-is-well-with-my-soul?lang=spa'),
      (1004, 'https://www.churchofjesuschrist.org/study/music/hymns-for-home-and-church/i-will-walk-with-jesus?lang=spa'),
      (1005, 'https://www.churchofjesuschrist.org/study/music/hymns-for-home-and-church/his-eye-is-on-the-sparrow?lang=spa'),
      (1006, 'https://www.churchofjesuschrist.org/study/music/hymns-for-home-and-church/think-a-sacred-song?lang=spa'),
      (1007, 'https://www.churchofjesuschrist.org/study/music/hymns-for-home-and-church/as-bread-is-broken?lang=spa'),
      (1008, 'https://www.churchofjesuschrist.org/study/music/hymns-for-home-and-church/bread-of-life-living-water?lang=spa'),
      (1009, 'https://www.churchofjesuschrist.org/study/music/hymns-for-home-and-church/gethsemane?lang=spa'),
      (1010, 'https://www.churchofjesuschrist.org/study/music/hymns-for-home-and-church/amazing-grace?lang=spa'),
      (1011, 'https://www.churchofjesuschrist.org/study/music/hymns-for-home-and-church/holding-hands-around-the-world?lang=spa'),
      (1012, 'https://www.churchofjesuschrist.org/study/music/hymns-for-home-and-church/anytime-anywhere?lang=spa'),
      (1013, 'https://www.churchofjesuschrist.org/study/music/hymns-for-home-and-church/gods-gracious-love?lang=spa'),
      (1014, 'https://www.churchofjesuschrist.org/study/music/hymns-for-home-and-church/my-shepherd-will-supply-my-need?lang=spa'),
      (1015, 'https://www.churchofjesuschrist.org/study/music/hymns-for-home-and-church/oh-the-deep-deep-love-of-jesus?lang=spa'),
      (1016, 'https://www.churchofjesuschrist.org/study/music/hymns-for-home-and-church/behold-the-wounds-in-jesus-hands?lang=spa'),
      (1017, 'https://www.churchofjesuschrist.org/study/music/hymns-for-home-and-church/this-is-the-christ?lang=spa'),
      (1018, 'https://www.churchofjesuschrist.org/study/music/hymns-for-home-and-church/come-lord-jesus?lang=spa'),
      (1019, 'https://www.churchofjesuschrist.org/study/music/hymns-for-home-and-church/to-love-like-thee-release-3?lang=spa'),
      (1020, 'https://www.churchofjesuschrist.org/study/music/hymns-for-home-and-church/softly-and-tenderly-jesus-is-calling-release-3?lang=spa'),
      (1021, 'https://www.churchofjesuschrist.org/study/music/hymns-for-home-and-church/i-know-that-my-savior-loves-me-release-3?lang=spa'),
      (1022, 'https://www.churchofjesuschrist.org/study/music/hymns-for-home-and-church/faith-in-every-footstep-release-3?lang=spa'),
      (1023, 'https://www.churchofjesuschrist.org/study/music/hymns-for-home-and-church/standing-on-the-promises-release-3?lang=spa'),
      (1024, 'https://www.churchofjesuschrist.org/study/music/hymns-for-home-and-church/i-have-faith-in-the-lord-jesus-christ-release-3?lang=spa'),
      (1025, 'https://www.churchofjesuschrist.org/study/music/hymns-for-home-and-church/take-my-heart-and-let-it-be-consecrated-release-3?lang=spa'),
      (1026, 'https://www.churchofjesuschrist.org/study/music/hymns-for-home-and-church/holy-places-release-3?lang=spa'),
      (1027, 'https://www.churchofjesuschrist.org/study/music/hymns-for-home-and-church/welcome-home-release-3?lang=spa'),
      (1028, 'https://www.churchofjesuschrist.org/study/music/hymns-for-home-and-church/this-little-light-of-mine-release-3?lang=spa'),
      (1029, 'https://www.churchofjesuschrist.org/study/music/hymns-for-home-and-church/i-cant-count-them-all-release-3?lang=spa'),
      (1030, 'https://www.churchofjesuschrist.org/study/music/hymns-for-home-and-church/close-as-a-quiet-prayer-release-3?lang=spa'),
      (1031, 'https://www.churchofjesuschrist.org/study/music/hymns-for-home-and-church/come-hear-the-word-the-lord-has-spoken-release-3?lang=spa'),
      (1032, 'https://www.churchofjesuschrist.org/study/music/hymns-for-home-and-church/look-unto-christ?lang=spa'),
      (1033, 'https://www.churchofjesuschrist.org/study/music/hymns-for-home-and-church/oh-how-great-is-our-joy?lang=spa'),
      (1034, 'https://www.churchofjesuschrist.org/study/music/hymns-for-home-and-church/im-a-pioneer-too?lang=spa'),
      (1035, 'https://www.churchofjesuschrist.org/study/music/hymns-for-home-and-church/as-i-keep-the-sabbath-day?lang=spa'),
      (1036, 'https://www.churchofjesuschrist.org/study/music/hymns-for-home-and-church/read-the-book-of-mormon-and-pray?lang=spa'),
      (1037, 'https://www.churchofjesuschrist.org/study/music/hymns-for-home-and-church/im-gonna-live-so-god-can-use-me?lang=spa'),
      (1038, 'https://www.churchofjesuschrist.org/study/music/hymns-for-home-and-church/the-lords-my-shepherd?lang=spa'),
      (1039, 'https://www.churchofjesuschrist.org/study/music/hymns-for-home-and-church/because?lang=spa'),
      (1040, 'https://www.churchofjesuschrist.org/study/music/hymns-for-home-and-church/his-voice-as-the-sound?lang=spa'),
      (1041, 'https://www.churchofjesuschrist.org/study/music/hymns-for-home-and-church/o-lord-who-gave-thy-life-for-me?lang=spa'),
      (1042, 'https://www.churchofjesuschrist.org/study/music/hymns-for-home-and-church/thou-gracious-god-whose-mercy-lends?lang=spa'),
      (1043, 'https://www.churchofjesuschrist.org/study/music/hymns-for-home-and-church/help-us-remember?lang=spa'),
      (1044, 'https://www.churchofjesuschrist.org/study/music/hymns-for-home-and-church/how-did-the-savior-minister?lang=spa'),
      (1045, 'https://www.churchofjesuschrist.org/study/music/hymns-for-home-and-church/jesus-is-the-way?lang=spa'),
      (1046, 'https://www.churchofjesuschrist.org/study/music/hymns-for-home-and-church/can-you-count-the-stars-in-heaven?lang=spa'),
      (1047, 'https://www.churchofjesuschrist.org/study/music/hymns-for-home-and-church/he-cares-for-me?lang=spa'),
      (1048, 'https://www.churchofjesuschrist.org/study/music/hymns-for-home-and-church/our-prayer-to-thee?lang=spa'),
      (1049, 'https://www.churchofjesuschrist.org/study/music/hymns-for-home-and-church/joseph-prayed-in-faith?lang=spa'),
      (1050, 'https://www.churchofjesuschrist.org/study/music/hymns-for-home-and-church/stand-by-me?lang=spa'),
      (1051, 'https://www.churchofjesuschrist.org/study/music/hymns-for-home-and-church/this-day-is-a-good-day-lord?lang=spa'),
      (1052, 'https://www.churchofjesuschrist.org/study/music/hymns-for-home-and-church/joyfully-bound?lang=spa'),
      (1053, 'https://www.churchofjesuschrist.org/study/music/hymns-for-home-and-church/my-covenants?lang=spa'),
      (1054, 'https://www.churchofjesuschrist.org/study/music/hymns-for-home-and-church/when-i-am-baptized?lang=spa'),
      (1055, 'https://www.churchofjesuschrist.org/study/music/hymns-for-home-and-church/the-power-of-the-holy-ghost?lang=spa'),
      (1056, 'https://www.churchofjesuschrist.org/study/music/hymns-for-home-and-church/elijah-and-the-still-small-voice?lang=spa'),
      (1057, 'https://www.churchofjesuschrist.org/study/music/hymns-for-home-and-church/jesus-is-my-shepherd?lang=spa'),
      (1058, 'https://www.churchofjesuschrist.org/study/music/hymns-for-home-and-church/my-song-in-the-night?lang=spa'),
      (1059, 'https://www.churchofjesuschrist.org/study/music/hymns-for-home-and-church/this-is-my-fathers-world?lang=spa'),
      (1060, 'https://www.churchofjesuschrist.org/study/music/hymns-for-home-and-church/build-an-ark?lang=spa'),
      (1061, 'https://www.churchofjesuschrist.org/study/music/hymns-for-home-and-church/love-will-bless-our-home?lang=spa'),
      (1062, 'https://www.churchofjesuschrist.org/study/music/hymns-for-home-and-church/lord-accept-our-humble-fast?lang=spa'),
      (1201, 'https://www.churchofjesuschrist.org/study/music/hymns-for-home-and-church/hail-the-day-that-sees-him-rise?lang=spa'),
      (1202, 'https://www.churchofjesuschrist.org/study/music/hymns-for-home-and-church/he-is-born-the-divine-christ-child?lang=spa'),
      (1203, 'https://www.churchofjesuschrist.org/study/music/hymns-for-home-and-church/what-child-is-this?lang=spa'),
      (1204, 'https://www.churchofjesuschrist.org/study/music/hymns-for-home-and-church/star-bright?lang=spa'),
      (1205, 'https://www.churchofjesuschrist.org/study/music/hymns-for-home-and-church/let-easter-anthems-ring-release-3?lang=spa'),
      (1206, 'https://www.churchofjesuschrist.org/study/music/hymns-for-home-and-church/were-you-there-release-3?lang=spa'),
      (1207, 'https://www.churchofjesuschrist.org/study/music/hymns-for-home-and-church/still-still-still?lang=spa'),
      (1208, 'https://www.churchofjesuschrist.org/study/music/hymns-for-home-and-church/go-tell-it-on-the-mountain?lang=spa'),
      (1209, 'https://www.churchofjesuschrist.org/study/music/hymns-for-home-and-church/little-baby-in-a-manger?lang=spa'),
      (1210, 'https://www.churchofjesuschrist.org/study/music/hymns-for-home-and-church/long-ago-within-a-garden?lang=spa')
    ) AS v(num, url)
    WHERE hymns.number = v.num
      AND (hymns.external_url IS NULL OR hymns.external_url = '')
  `);

  // Insert Canciones para los Niños (primaria) — hymnbook='primaria'
  // Letter-variant numbers use X*1000+letter_index to avoid conflicts within hymnbook
  await db.execute(sql`
    INSERT INTO hymns (number, number_display, hymnbook, lang, title, external_url) VALUES
      (2,      NULL,    'primaria', 'es', 'Soy un hijo de Dios',                        'https://www.churchofjesuschrist.org/study/manual/childrens-songbook/i-am-a-child-of-god?lang=spa'),
      (4,      NULL,    'primaria', 'es', 'Niños de todo el mundo',                     'https://www.churchofjesuschrist.org/study/manual/childrens-songbook/children-all-over-the-world?lang=spa'),
      (6,      NULL,    'primaria', 'es', 'Oración de un niño',                         'https://www.churchofjesuschrist.org/study/manual/childrens-songbook/a-childs-prayer?lang=spa'),
      (8,      NULL,    'primaria', 'es', 'Dios vive',                                  'https://www.churchofjesuschrist.org/study/manual/childrens-songbook/i-know-my-father-lives?lang=spa'),
      (9,      NULL,    'primaria', 'es', 'Doy gracias, oh Padre',                      'https://www.churchofjesuschrist.org/study/manual/childrens-songbook/i-thank-thee-dear-father?lang=spa'),
      (10,     NULL,    'primaria', 'es', 'Con reverencia',                             'https://www.churchofjesuschrist.org/study/manual/childrens-songbook/father-i-will-reverent-be?lang=spa'),
      (11,     NULL,    'primaria', 'es', 'Con quietud',                                'https://www.churchofjesuschrist.org/study/manual/childrens-songbook/reverently-quietly?lang=spa'),
      (12,     NULL,    'primaria', 'es', 'La reverencia es amor',                      'https://www.churchofjesuschrist.org/study/manual/childrens-songbook/reverence-is-love?lang=spa'),
      (13,     NULL,    'primaria', 'es', 'Reverencia mostraré',                        'https://www.churchofjesuschrist.org/study/manual/childrens-songbook/i-will-try-to-be-reverent?lang=spa'),
      (14,     NULL,    'primaria', 'es', '¿Puede un niño como yo?',                   'https://www.churchofjesuschrist.org/study/manual/childrens-songbook/can-a-little-child-like-me?lang=spa'),
      (15,     NULL,    'primaria', 'es', 'Demos gracias al padre',                     'https://www.churchofjesuschrist.org/study/manual/childrens-songbook/thanks-to-our-father?lang=spa'),
      (16,     NULL,    'primaria', 'es', 'Mi Padre Celestial me ama',                  'https://www.churchofjesuschrist.org/study/manual/childrens-songbook/my-heavenly-father-loves-me?lang=spa'),
      (18001,  '18a',   'primaria', 'es', 'Rondó de gracias',                           'https://www.churchofjesuschrist.org/study/manual/childrens-songbook/for-health-and-strength-round?lang=spa'),
      (18002,  '18b',   'primaria', 'es', 'Al orar',                                    'https://www.churchofjesuschrist.org/study/manual/childrens-songbook/we-bow-our-heads?lang=spa'),
      (20,     NULL,    'primaria', 'es', 'Mandó a Su Hijo',                            'https://www.churchofjesuschrist.org/study/manual/childrens-songbook/he-sent-his-son?lang=spa'),
      (22,     NULL,    'primaria', 'es', 'Al irse a Belén José',                       'https://www.churchofjesuschrist.org/study/manual/childrens-songbook/when-joseph-went-to-bethlehem?lang=spa'),
      (24,     NULL,    'primaria', 'es', 'La Nochebuena',                              'https://www.churchofjesuschrist.org/study/manual/childrens-songbook/stars-were-gleaming?lang=spa'),
      (25,     NULL,    'primaria', 'es', 'Dentro de un establo humilde',               'https://www.churchofjesuschrist.org/study/manual/childrens-songbook/once-within-a-lowly-stable?lang=spa'),
      (26,     NULL,    'primaria', 'es', 'Jesús en pesebre',                           'https://www.churchofjesuschrist.org/study/manual/childrens-songbook/away-in-a-manger?lang=spa'),
      (28,     NULL,    'primaria', 'es', 'El arrullo de María',                        'https://www.churchofjesuschrist.org/study/manual/childrens-songbook/marys-lullaby?lang=spa'),
      (30,     NULL,    'primaria', 'es', 'Duerme, mi nene',                            'https://www.churchofjesuschrist.org/study/manual/childrens-songbook/oh-hush-thee-my-baby?lang=spa'),
      (32,     NULL,    'primaria', 'es', 'Canto de Navidad',                           'https://www.churchofjesuschrist.org/study/manual/childrens-songbook/the-nativity-song?lang=spa'),
      (34,     NULL,    'primaria', 'es', 'Pequeño niño fue Jesús',                     'https://www.churchofjesuschrist.org/study/manual/childrens-songbook/jesus-once-was-a-little-child?lang=spa'),
      (35,     NULL,    'primaria', 'es', 'Me gusta pensar en el Señor',                'https://www.churchofjesuschrist.org/study/manual/childrens-songbook/i-think-when-i-read-that-sweet-story?lang=spa'),
      (36,     NULL,    'primaria', 'es', 'Dime la historia de Cristo',                 'https://www.churchofjesuschrist.org/study/manual/childrens-songbook/tell-me-the-stories-of-jesus?lang=spa'),
      (37,     NULL,    'primaria', 'es', 'Fiel amigo es Jesús',                        'https://www.churchofjesuschrist.org/study/manual/childrens-songbook/jesus-is-our-loving-friend?lang=spa'),
      (38,     NULL,    'primaria', 'es', 'Cristo me manda que brille',                 'https://www.churchofjesuschrist.org/study/manual/childrens-songbook/jesus-wants-me-for-a-sunbeam?lang=spa'),
      (39,     NULL,    'primaria', 'es', 'Ama a todos, dijo el Señor',                 'https://www.churchofjesuschrist.org/study/manual/childrens-songbook/jesus-said-love-everyone?lang=spa'),
      (40,     NULL,    'primaria', 'es', 'Yo trato de ser como Cristo',                'https://www.churchofjesuschrist.org/study/manual/childrens-songbook/im-trying-to-be-like-jesus?lang=spa'),
      (42,     NULL,    'primaria', 'es', 'Siento el amor de mi Salvador',              'https://www.churchofjesuschrist.org/study/manual/childrens-songbook/i-feel-my-saviors-love?lang=spa'),
      (44,     NULL,    'primaria', 'es', 'Resucitó Jesús',                             'https://www.churchofjesuschrist.org/study/manual/childrens-songbook/jesus-has-risen?lang=spa'),
      (45,     NULL,    'primaria', 'es', '¿Vivió Jesús una vez más?',                 'https://www.churchofjesuschrist.org/study/manual/childrens-songbook/did-jesus-really-live-again?lang=spa'),
      (46,     NULL,    'primaria', 'es', 'Cuando venga Jesús',                         'https://www.churchofjesuschrist.org/study/manual/childrens-songbook/when-he-comes-again?lang=spa'),
      (48,     NULL,    'primaria', 'es', 'La Iglesia de Jesucristo',                   'https://www.churchofjesuschrist.org/study/manual/childrens-songbook/the-church-of-jesus-christ?lang=spa'),
      (50,     NULL,    'primaria', 'es', 'La fe',                                      'https://www.churchofjesuschrist.org/study/manual/childrens-songbook/faith?lang=spa'),
      (52,     NULL,    'primaria', 'es', 'Saber perdonar',                             'https://www.churchofjesuschrist.org/study/manual/childrens-songbook/help-me-dear-father?lang=spa'),
      (53,     NULL,    'primaria', 'es', 'Cuando me bautice',                          'https://www.churchofjesuschrist.org/study/manual/childrens-songbook/when-i-am-baptized?lang=spa'),
      (54,     NULL,    'primaria', 'es', 'El bautismo',                                'https://www.churchofjesuschrist.org/study/manual/childrens-songbook/baptism?lang=spa'),
      (56,     NULL,    'primaria', 'es', 'El Espíritu Santo',                          'https://www.churchofjesuschrist.org/study/manual/childrens-songbook/the-holy-ghost?lang=spa'),
      (57,     NULL,    'primaria', 'es', 'En la primavera',                            'https://www.churchofjesuschrist.org/study/manual/childrens-songbook/on-a-golden-springtime?lang=spa'),
      (58,     NULL,    'primaria', 'es', 'Sigue al Profeta',                           'https://www.churchofjesuschrist.org/study/manual/childrens-songbook/follow-the-prophet?lang=spa'),
      (60,     NULL,    'primaria', 'es', 'El sacerdocio se restauró',                  'https://www.churchofjesuschrist.org/study/manual/childrens-songbook/the-priesthood-is-restored?lang=spa'),
      (61,     NULL,    'primaria', 'es', 'Las planchas de oro',                        'https://www.churchofjesuschrist.org/study/manual/childrens-songbook/the-golden-plates?lang=spa'),
      (62,     NULL,    'primaria', 'es', 'Historias del Libro de Mormón',              'https://www.churchofjesuschrist.org/study/manual/childrens-songbook/book-of-mormon-stories?lang=spa'),
      (63,     NULL,    'primaria', 'es', 'Los libros del Libro de Mormón',             'https://www.churchofjesuschrist.org/study/manual/childrens-songbook/the-books-in-the-book-of-mormon?lang=spa'),
      (64,     NULL,    'primaria', 'es', 'El valor de Nefi',                           'https://www.churchofjesuschrist.org/study/manual/childrens-songbook/nephis-courage?lang=spa'),
      (66,     NULL,    'primaria', 'es', 'Escudriñar, meditar y orar',                 'https://www.churchofjesuschrist.org/study/manual/childrens-songbook/search-ponder-and-pray?lang=spa'),
      (67,     NULL,    'primaria', 'es', 'Buscaré al Señor',                           'https://www.churchofjesuschrist.org/study/manual/childrens-songbook/seek-the-lord-early?lang=spa'),
      (68,     NULL,    'primaria', 'es', 'Siempre obedece los mandamientos',           'https://www.churchofjesuschrist.org/study/manual/childrens-songbook/keep-the-commandments?lang=spa'),
      (70,     NULL,    'primaria', 'es', 'Hazme andar en la luz',                      'https://www.churchofjesuschrist.org/study/manual/childrens-songbook/teach-me-to-walk-in-the-light?lang=spa'),
      (71,     NULL,    'primaria', 'es', 'Obediencia',                                 'https://www.churchofjesuschrist.org/study/manual/childrens-songbook/quickly-ill-obey?lang=spa'),
      (72,     NULL,    'primaria', 'es', 'Voy a vivir el Evangelio',                   'https://www.churchofjesuschrist.org/study/manual/childrens-songbook/i-want-to-live-the-gospel?lang=spa'),
      (73,     NULL,    'primaria', 'es', 'El Señor me dio un templo',                  'https://www.churchofjesuschrist.org/study/manual/childrens-songbook/the-lord-gave-me-a-temple?lang=spa'),
      (74,     NULL,    'primaria', 'es', 'Amad a otros',                               'https://www.churchofjesuschrist.org/study/manual/childrens-songbook/love-one-another?lang=spa'),
      (75,     NULL,    'primaria', 'es', 'Dime, Señor',                                'https://www.churchofjesuschrist.org/study/manual/childrens-songbook/tell-me-dear-lord?lang=spa'),
      (76,     NULL,    'primaria', 'es', 'Donde hay amor',                             'https://www.churchofjesuschrist.org/study/manual/childrens-songbook/where-love-is?lang=spa'),
      (78,     NULL,    'primaria', 'es', 'Contigo iré',                                'https://www.churchofjesuschrist.org/study/manual/childrens-songbook/ill-walk-with-you?lang=spa'),
      (80,     NULL,    'primaria', 'es', 'Muestra valor',                              'https://www.churchofjesuschrist.org/study/manual/childrens-songbook/dare-to-do-right?lang=spa'),
      (81,     NULL,    'primaria', 'es', 'Defiende el bien',                           'https://www.churchofjesuschrist.org/study/manual/childrens-songbook/stand-for-the-right?lang=spa'),
      (82,     NULL,    'primaria', 'es', 'Escojamos lo correcto',                      'https://www.churchofjesuschrist.org/study/manual/childrens-songbook/choose-the-right-way?lang=spa'),
      (83,     NULL,    'primaria', 'es', 'La bondad por mí empieza',                   'https://www.churchofjesuschrist.org/study/manual/childrens-songbook/kindness-begins-with-me?lang=spa'),
      (84,     NULL,    'primaria', 'es', 'Yo soy como estrella',                       'https://www.churchofjesuschrist.org/study/manual/childrens-songbook/i-am-like-a-star?lang=spa'),
      (85,     NULL,    'primaria', 'es', 'Voy a ser valiente',                         'https://www.churchofjesuschrist.org/study/manual/childrens-songbook/i-will-be-valiant?lang=spa'),
      (86,     NULL,    'primaria', 'es', 'El plan de Dios puedo seguir',               'https://www.churchofjesuschrist.org/study/manual/childrens-songbook/i-will-follow-gods-plan?lang=spa'),
      (88,     NULL,    'primaria', 'es', 'Joven digno y hábil seré',                   'https://www.churchofjesuschrist.org/study/manual/childrens-songbook/a-young-man-prepared?lang=spa'),
      (90,     NULL,    'primaria', 'es', 'Yo quiero ser un misionero ya',              'https://www.churchofjesuschrist.org/study/manual/childrens-songbook/i-want-to-be-a-missionary-now?lang=spa'),
      (91,     NULL,    'primaria', 'es', 'Espero ser llamado a una misión',            'https://www.churchofjesuschrist.org/study/manual/childrens-songbook/i-hope-they-call-me-on-a-mission?lang=spa'),
      (92,     NULL,    'primaria', 'es', 'Llevaremos Su verdad al mundo (El ejército de Helamán)', 'https://www.churchofjesuschrist.org/study/manual/childrens-songbook/well-bring-the-world-his-truth-army-of-helaman?lang=spa'),
      (94,     NULL,    'primaria', 'es', 'Llamados a servir',                          'https://www.churchofjesuschrist.org/study/manual/childrens-songbook/called-to-serve?lang=spa'),
      (96,     NULL,    'primaria', 'es', 'Brilla',                                     'https://www.churchofjesuschrist.org/study/manual/childrens-songbook/shine-on?lang=spa'),
      (98,     NULL,    'primaria', 'es', 'Las familias pueden ser eternas',            'https://www.churchofjesuschrist.org/study/manual/childrens-songbook/families-can-be-together-forever?lang=spa'),
      (99,     NULL,    'primaria', 'es', 'Me encanta ver el templo',                   'https://www.churchofjesuschrist.org/study/manual/childrens-songbook/i-love-to-see-the-temple?lang=spa'),
      (100,    NULL,    'primaria', 'es', 'Estoy haciendo mi historia familiar',        'https://www.churchofjesuschrist.org/study/manual/childrens-songbook/family-history-i-am-doing-it?lang=spa'),
      (101,    NULL,    'primaria', 'es', 'Oración familiar',                           'https://www.churchofjesuschrist.org/study/manual/childrens-songbook/family-prayer?lang=spa'),
      (102,    NULL,    'primaria', 'es', 'Allí donde hay amor',                        'https://www.churchofjesuschrist.org/study/manual/childrens-songbook/love-is-spoken-here?lang=spa'),
      (104,    NULL,    'primaria', 'es', 'Una familia feliz',                          'https://www.churchofjesuschrist.org/study/manual/childrens-songbook/a-happy-family?lang=spa'),
      (105,    NULL,    'primaria', 'es', 'El sábado',                                  'https://www.churchofjesuschrist.org/study/manual/childrens-songbook/saturday?lang=spa'),
      (106,    NULL,    'primaria', 'es', 'Los nombres más bellos',                     'https://www.churchofjesuschrist.org/study/manual/childrens-songbook/the-dearest-names?lang=spa'),
      (107,    NULL,    'primaria', 'es', 'Madre, te amo',                              'https://www.churchofjesuschrist.org/study/manual/childrens-songbook/mother-i-love-you?lang=spa'),
      (108001, '108a',  'primaria', 'es', 'Madrecita de mi amor',                       'https://www.churchofjesuschrist.org/study/manual/childrens-songbook/mother-dear?lang=spa'),
      (108002, '108b',  'primaria', 'es', 'Cuando ayudamos',                            'https://www.churchofjesuschrist.org/study/manual/childrens-songbook/when-were-helping?lang=spa'),
      (109,    NULL,    'primaria', 'es', 'Por campos de trébol paseo',                 'https://www.churchofjesuschrist.org/study/manual/childrens-songbook/i-often-go-walking?lang=spa'),
      (110,    NULL,    'primaria', 'es', 'Cuando papá vuelve',                         'https://www.churchofjesuschrist.org/study/manual/childrens-songbook/daddys-homecoming?lang=spa'),
      (111,    NULL,    'primaria', 'es', 'Mi papá',                                    'https://www.churchofjesuschrist.org/study/manual/childrens-songbook/my-dad?lang=spa'),
      (112,    NULL,    'primaria', 'es', 'La abuelita',                                'https://www.churchofjesuschrist.org/study/manual/childrens-songbook/grandmother?lang=spa'),
      (113,    NULL,    'primaria', 'es', 'Cuando abuelito viene',                      'https://www.churchofjesuschrist.org/study/manual/childrens-songbook/when-grandpa-comes?lang=spa'),
      (114,    NULL,    'primaria', 'es', 'Con un cantar',                              'https://www.churchofjesuschrist.org/study/manual/childrens-songbook/sing-your-way-home?lang=spa'),
      (116,    NULL,    'primaria', 'es', 'El arroyito da',                             'https://www.churchofjesuschrist.org/study/manual/childrens-songbook/give-said-the-little-stream?lang=spa'),
      (117,    NULL,    'primaria', 'es', 'Cae la lluvia alrededor',                    'https://www.churchofjesuschrist.org/study/manual/childrens-songbook/rain-is-falling-all-around?lang=spa'),
      (118,    NULL,    'primaria', 'es', 'Palomitas de maíz',                          'https://www.churchofjesuschrist.org/study/manual/childrens-songbook/popcorn-popping?lang=spa'),
      (119,    NULL,    'primaria', 'es', 'Las semillas duermen',                       'https://www.churchofjesuschrist.org/study/manual/childrens-songbook/little-seeds-lie-fast-asleep?lang=spa'),
      (120,    NULL,    'primaria', 'es', '¿Qué haces en el verano?',                  'https://www.churchofjesuschrist.org/study/manual/childrens-songbook/oh-what-do-you-do-in-the-summertime?lang=spa'),
      (121,    NULL,    'primaria', 'es', 'Éste era un mono',                           'https://www.churchofjesuschrist.org/study/manual/childrens-songbook/once-there-was-a-snowman?lang=spa'),
      (122,    NULL,    'primaria', 'es', 'El mundo es glorioso',                       'https://www.churchofjesuschrist.org/study/manual/childrens-songbook/i-think-the-world-is-glorious?lang=spa'),
      (123,    NULL,    'primaria', 'es', '¡El mundo es tan bello!',                   'https://www.churchofjesuschrist.org/study/manual/childrens-songbook/the-world-is-so-lovely?lang=spa'),
      (124,    NULL,    'primaria', 'es', 'Alza al cielo el son',                       'https://www.churchofjesuschrist.org/study/manual/childrens-songbook/lift-up-your-voice-and-sing?lang=spa'),
      (125,    NULL,    'primaria', 'es', 'Si te sientes feliz',                        'https://www.churchofjesuschrist.org/study/manual/childrens-songbook/if-youre-happy?lang=spa'),
      (126,    NULL,    'primaria', 'es', 'Mis manitas',                                'https://www.churchofjesuschrist.org/study/manual/childrens-songbook/i-have-two-little-hands?lang=spa'),
      (127,    NULL,    'primaria', 'es', 'Me doblo',                                   'https://www.churchofjesuschrist.org/study/manual/childrens-songbook/hinges?lang=spa'),
      (128,    NULL,    'primaria', 'es', 'Sonrisas',                                   'https://www.churchofjesuschrist.org/study/manual/childrens-songbook/smiles?lang=spa'),
      (129001, '129a',  'primaria', 'es', 'Cabeza, cara, hombros, pies',                'https://www.churchofjesuschrist.org/study/manual/childrens-songbook/head-shoulders-knees-and-toes?lang=spa'),
      (129002, '129b',  'primaria', 'es', 'Qué divertido es',                           'https://www.churchofjesuschrist.org/study/manual/childrens-songbook/fun-to-do?lang=spa'),
      (130,    NULL,    'primaria', 'es', '¡Hola!',                                    'https://www.churchofjesuschrist.org/study/manual/childrens-songbook/hello-song?lang=spa'),
      (131,    NULL,    'primaria', 'es', 'Los colores de nuestra Primaria',            'https://www.churchofjesuschrist.org/study/manual/childrens-songbook/our-primary-colors?lang=spa'),
      (132,    NULL,    'primaria', 'es', 'El sabio y el imprudente',                   'https://www.churchofjesuschrist.org/study/manual/childrens-songbook/the-wise-man-and-the-foolish-man?lang=spa'),
      (133,    NULL,    'primaria', 'es', 'Cumpliste años (Rondó)',                     'https://www.churchofjesuschrist.org/study/manual/childrens-songbook/youve-had-a-birthday-round?lang=spa'),
      (134,    NULL,    'primaria', 'es', 'Feliz, feliz cumpleaños',                    'https://www.churchofjesuschrist.org/study/manual/childrens-songbook/happy-happy-birthday?lang=spa'),
      (136,    NULL,    'primaria', 'es', 'Pioneros fieles',                            'https://www.churchofjesuschrist.org/study/manual/childrens-songbook/the-handcart-song?lang=spa'),
      (137,    NULL,    'primaria', 'es', 'Niños pioneros',                             'https://www.churchofjesuschrist.org/study/manual/childrens-songbook/pioneer-children-sang-as-they-walked?lang=spa'),
      (138,    NULL,    'primaria', 'es', 'Para ser pionero',                           'https://www.churchofjesuschrist.org/study/manual/childrens-songbook/to-be-a-pioneer?lang=spa'),
      (139,    NULL,    'primaria', 'es', 'Mi mamá nos da amor',                        'https://www.churchofjesuschrist.org/study/manual/childrens-songbook/loving-mother-kind-and-true?lang=spa'),
      (140,    NULL,    'primaria', 'es', 'Belleza por doquier',                        'https://www.churchofjesuschrist.org/study/manual/childrens-songbook/beauty-everywhere?lang=spa'),
      (141,    NULL,    'primaria', 'es', 'Hazlo conmigo',                              'https://www.churchofjesuschrist.org/study/manual/childrens-songbook/do-as-im-doing?lang=spa'),
      (142,    NULL,    'primaria', 'es', 'En el prado',                                'https://www.churchofjesuschrist.org/study/manual/childrens-songbook/in-the-meadow?lang=spa'),
      (144,    NULL,    'primaria', 'es', 'A mi madre',                                 'https://www.churchofjesuschrist.org/study/manual/childrens-songbook/my-mother?lang=spa'),
      (145,    NULL,    'primaria', 'es', 'Como el sol en la mañana',                   'https://www.churchofjesuschrist.org/study/manual/childrens-songbook/my-mother-dear?lang=spa'),
      (146,    NULL,    'primaria', 'es', 'Estrella de luz',                            'https://www.churchofjesuschrist.org/study/manual/childrens-songbook/star-bright?lang=spa'),
      (148,    NULL,    'primaria', 'es', 'Viví en los cielos',                         'https://www.churchofjesuschrist.org/study/manual/childrens-songbook/i-lived-in-heaven?lang=spa')
    ON CONFLICT (number, hymnbook) DO NOTHING
  `);
}
